# Generated by Django 4.1.2 on 2022-12-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_airport_id_alter_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер рейса'),
        ),
    ]
